version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: odoo_instance2
      POSTGRES_USER: odoo_instance2
      POSTGRES_PASSWORD: odoo_instance2
  web:
    image: odoo:14
    depends_on:
      - db
    ports:
      - "8070:8069"
    environment:
      HOST: db
      USER: odoo_instance2
      PASSWORD: odoo_instance2
      DB_NAME: odoo_instance2
